# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_by',
            field=models.DateField(),
        ),
    ]
