# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170624_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_by',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
